// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feed_main.proto

#ifndef PROTOBUF_feed_5fmain_2eproto__INCLUDED
#define PROTOBUF_feed_5fmain_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace idl {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_feed_5fmain_2eproto();
void protobuf_AssignDesc_feed_5fmain_2eproto();
void protobuf_ShutdownFile_feed_5fmain_2eproto();

class MainFeedAction;

enum MainFeedOption {
  ADD = 0,
  REMOVE = 1,
  ACK = 2
};
bool MainFeedOption_IsValid(int value);
const MainFeedOption MainFeedOption_MIN = ADD;
const MainFeedOption MainFeedOption_MAX = ACK;
const int MainFeedOption_ARRAYSIZE = MainFeedOption_MAX + 1;

const ::google::protobuf::EnumDescriptor* MainFeedOption_descriptor();
inline const ::std::string& MainFeedOption_Name(MainFeedOption value) {
  return ::google::protobuf::internal::NameOfEnum(
    MainFeedOption_descriptor(), value);
}
inline bool MainFeedOption_Parse(
    const ::std::string& name, MainFeedOption* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MainFeedOption>(
    MainFeedOption_descriptor(), name, value);
}
// ===================================================================

class MainFeedAction : public ::google::protobuf::Message {
 public:
  MainFeedAction();
  virtual ~MainFeedAction();

  MainFeedAction(const MainFeedAction& from);

  inline MainFeedAction& operator=(const MainFeedAction& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MainFeedAction& default_instance();

  void Swap(MainFeedAction* other);

  // implements Message ----------------------------------------------

  MainFeedAction* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MainFeedAction& from);
  void MergeFrom(const MainFeedAction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .idl.MainFeedOption option = 1;
  inline bool has_option() const;
  inline void clear_option();
  static const int kOptionFieldNumber = 1;
  inline ::idl::MainFeedOption option() const;
  inline void set_option(::idl::MainFeedOption value);

  // optional string data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const char* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:idl.MainFeedAction)
 private:
  inline void set_has_option();
  inline void clear_has_option();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* data_;
  int option_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_feed_5fmain_2eproto();
  friend void protobuf_AssignDesc_feed_5fmain_2eproto();
  friend void protobuf_ShutdownFile_feed_5fmain_2eproto();

  void InitAsDefaultInstance();
  static MainFeedAction* default_instance_;
};
// ===================================================================


// ===================================================================

// MainFeedAction

// required .idl.MainFeedOption option = 1;
inline bool MainFeedAction::has_option() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MainFeedAction::set_has_option() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MainFeedAction::clear_has_option() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MainFeedAction::clear_option() {
  option_ = 0;
  clear_has_option();
}
inline ::idl::MainFeedOption MainFeedAction::option() const {
  return static_cast< ::idl::MainFeedOption >(option_);
}
inline void MainFeedAction::set_option(::idl::MainFeedOption value) {
  assert(::idl::MainFeedOption_IsValid(value));
  set_has_option();
  option_ = value;
}

// optional string data = 2;
inline bool MainFeedAction::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MainFeedAction::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MainFeedAction::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MainFeedAction::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& MainFeedAction::data() const {
  return *data_;
}
inline void MainFeedAction::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void MainFeedAction::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void MainFeedAction::set_data(const char* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MainFeedAction::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* MainFeedAction::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MainFeedAction::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace idl

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::idl::MainFeedOption>() {
  return ::idl::MainFeedOption_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_feed_5fmain_2eproto__INCLUDED
